version: "3.8"

services:
  # web:
  #   build: .
  #   command: npm run dev
  #   volumes:
  #     - .:/usr/app
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_USER=jc
  #     - DB_PASSWORD=password
  #     - DB_HOST=db
  #     - DB_PORT=5555
  #     - DB_DATABASE=template

  db:
    container_name: pern-stack-template-db
    image: postgres
    restart: always
    ports:
      - 5555:5555
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: template
    volumes: 
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: pern-stack-tempalte-mypgadmin
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=jcoles1155@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
